RpcAddr="wss://devnet-rpc.cess.cloud/ws/"
ServerPort="8081"
AccountSeed="plug increase image genius rabbit unable once sponsor tail castle wet fan"
AccountID="cXgP2nH3GkFweiAUcPFWJjxRdiScooTneMgdowKe6Lfe3hQQ8"
MaxTxPoolSize=128
#order expiration(hours)
ExpDate=24